In [9]:
import numpy as np
import pandas as pd
from sklearn import *

In [10]:
data = np.loadtxt('./clase3v2.csv', delimiter = ';')

El dataset 'clase3v2.csv' es un dataset sintético para un problema de regresión. Su columna target es la última. 

# Ejercicio 1

Crear una función que remueva filas y columnas con NaNs.

In [3]:
np.isnan(data).any(axis=1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [4]:
~np.isnan(data).any(axis=1)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [5]:
data.shape

(100, 7)

In [6]:
def removefilas(data):
    d = data[~np.isnan(data).any(axis=1), :]
    return d

In [7]:
def removecolumns(data):
    d = data[:, ~np.isnan(data).any(axis=0)]
    return d

In [8]:
data_nan = removenans(data)

NameError: name 'removenans' is not defined

In [66]:
data_nan.shape

(75, 7)

# Ejercicio 2

Crear una función que reemplace NaN por la media y otra con la mediana de la columna.

In [41]:
np.nanmean(data, axis=0)

array([ 2.27198551,  1.28481564,  4.18456924,  1.10395579, -0.63116864,
       -3.83479401,  1.5093118 ])

In [43]:
data2 = data.copy()

In [67]:
np.nan_to_num?

In [70]:
data2 = np.nan_to_num(data2,False, np.nanmean(data, axis=0))

In [48]:
np.isnan(data2).sum()

0

In [50]:
np.isnan(data)

array([[False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False,  True, False, False],
       [False, False,  True, False, False, False, False],
       [False, False,  True, False, False, False, False],
       [False,

In [53]:
np.nanmean(data, axis=0)[4]

-0.6311686415689359

In [51]:
data2[:,4]

array([-0.63116864, -0.63116864, -0.63116864, -0.63116864, -0.63116864,
       -0.63116864, -0.63116864, -0.63116864, -0.63116864, -0.63116864,
       -0.63116864, -0.63116864, -0.63116864, -0.63116864, -0.63116864,
       -0.34701968, -0.90534368, -0.87100907, -0.8316363 ,  1.73002857,
        1.72919579, -4.66404334, -3.66221363, -4.8259839 , -0.34138897,
       -7.62384533, -2.42730589,  6.11679773,  1.34285918,  2.72547311,
        1.19371771, -1.29957288, -0.68483286, -2.12225063, -4.21532956,
        4.30003861, -1.73669765, -0.14175759,  0.16368406,  1.90101285,
        0.09012476,  1.28458725,  3.36275505,  4.62508432, -0.41679513,
        2.12395748, -1.01385569, -0.51066842, -0.82659342, -5.51494607,
        1.02619283,  2.07782599, -3.84152758, -4.51766639, -0.93921135,
       -3.77904391, -2.47518076,  0.01764788,  0.50988832, -0.16677125,
       -7.48469417, -7.40287074,  2.83986748,  3.13346525, -1.44646454,
       -4.16464641, -1.27630652,  6.57561764, -2.16817612, -4.65

In [ ]:
def replace_mean(d):
    
    return NotImplemented

# Ejercicio 3

Crear una función que separe los datos en train-validation-test 70-20-10


Hints: 

* Usar Indexing y slicing
* Usar np.random.[...]

In [ ]:

def split(data, percentage):  # 0.8
    X = self.dataset['income']
    y = self.dataset['happiness']

    # X.shape[0] cantidad de observ

    permuted_idxs = np.random.permutation(X.shape[0])

    train_idxs = permuted_idxs[0:int(0.7 * X.shape[0])]
    val_idxs =  permuted_idxs[int(0.7 * X.shape[0]: int(0.9 * X.shape[0])]
    test_idxs = permuted_idxs[int(0.9 * X.shape[0]):]
    # [9,117,85,41,1,6]

    X_train = X[train_idxs]
    X_val = X[val_idxs]                          
    X_test = X[test_idxs]

    y_train = y[train_idxs]
    y_val = y[val_idxs] 
    y_test = y[test_idxs]

    return X_train, X_val ... etc

# Ejercicio 4

Tomar una matrix numpy y agregarle **una columna y una fila** de 1's

Puede usar 

$$
  A =
  \left[ {\begin{array}{ccc}
    -2 & -4 & 2 \\
    -2 & 1 & 2 \\
    4 & 2 & 5 \\
  \end{array} } \right]
$$



In [ ]:
np.ones()
np.hstack()
np.vstack()

# Ejercicio 5

Implementar la función regresión lineal **SIN término independiente**. 

Considerar el caso en que $X^TX$ no sea invertible. 


In [ ]:
def regresion_lineal(x,y):
    return NotImplemented

# Ejercicio 6

Ajustar la regresión lineal a los datos cargados. 

# Ejercicio 7

Graficar los puntos y la recta ajustada.

# Ejercicio 8 

Repetir el ajuste anterior utilizando la regresión lineal de sklearn sin ordenada.