# Trabajo integrador - Parte 1
## Python y Numpy

**Nombre**:

In [1]:
import numpy as np

## Ejercicio 1

Dada una matriz en formato *numpy array*, donde cada fila de la matriz representa un vector matemático, se requiere computar las normas $l_0$, $l_1$, $l_2$, $l_{\infty}$, según la siguientes definiciones:

\begin{equation}
    ||\mathbf{x}||^{p} = \bigg(\sum_{j=1}^{n}{|x_i|^p}\bigg)^{\frac{1}{p}}
\end{equation}

con los casos especiales para $p=0$ y $p=\infty$ siendo:

\begin{equation}
    \begin{array}{rcl}
        ||\mathbf{x}||_0 & = & \bigg(\sum_{j=1 \wedge x_j != 0}{|x_i|}\bigg)\\
        ||\mathbf{x}||_{\infty} & = & \max_{i}{|x_i|}\\
    \end{array}
\end{equation}

In [29]:
matrix = np.array([[0, -1, 2], [3, 4, 5], [6, 7, 8]])

print("Matriz:\n", matrix, "\n")
print("Vector 1:\n", matrix[0], "\n")
print("Vector 2:\n", matrix[1], "\n")
print("Vector 3:\n", matrix[2], "\n")

#test de valores absolutos
print("Abs:\n", np.abs(matrix), "\n")

# Una norma para vectores o matrices, es una medida de la "magnitud" o " tamaño" de éstos (sacado de wiki).
def apply_norm(matrix, p):
    norm_val = None
    if p == 0:
        # En la norma 0 se pide la sumatoria de todos los valores de los arrays que componen la matriz, exceptuando el 0
        norm_val = np.sum(np.abs(matrix))
    elif p == np.inf:
        # En la norma infinito se pide el valor máximo de todos los elemtos de los vectores de la matriz
        norm_val = np.max(np.abs(matrix))
    else:
        # para cualquier otro valor que tome P se pide la sumatoria cada uno de los valores de los arrays, que
        # componenen la matriz, elevado a P, y a ese resultado se lo eleva a 1/P
        norm_val = np.sum(np.abs(matrix)**p)**(1/p)
    return norm_val

print("Norm L0", apply_norm(matrix, 0))
print("Norm L1", apply_norm(matrix, 1))
print("Norm L2", apply_norm(matrix, 2))
print("Norm L infinity", apply_norm(matrix, np.inf))


Matriz:
 [[ 0 -1  2]
 [ 3  4  5]
 [ 6  7  8]] 

Vector 1:
 [ 0 -1  2] 

Vector 2:
 [3 4 5] 

Vector 3:
 [6 7 8] 

Abs:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Norm L0 36
Norm L1 36.0
Norm L2 14.2828568570857
Norm L infinity 8


## Ejercicio 2

En clasificación contamos con dos arreglos, la “verdad” y la “predicción”. Cada elemento de los arreglos pueden tomar dos valores, “True” (representado por 1) y “False” (representado por 0). Entonces podemos definir 4 variables:

* True Positive (TP): El valor verdadero es 1 y el valor predicho es 1
* True Negative (TN): El valor verdadero es 0 y el valor predicho es 0
* False Positive (FP): El valor verdadero es 0 y el valor predicho es 1
* False Negative (FN): El valor verdadero es 1 y el valor predicho es 0

A partir de esto definimos:

* Precision = TP / (TP + FP)
* Recall = TP / (TP + FN)
* Accuracy = (TP + TN) / (TP + TN + FP + FN)
 
Calcular las 3 métricas con Numpy y operaciones vectorizadas.

In [ ]:
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

## Ejercicio 3

Crear una función que separe los datos en train-validation-test. Debe recibir de parametros:

- X: Array o Dataframe que contiene los datos de entrada del sistema.
- y: Array o Dataframe que contiene la(s) variable(s) target del problema.
- train_percentage: _float_ el porcentaje de training.
- test_percentage: _float_ el porcentaje de testing.
- val_percentage: _float_ el porcentaje de validación.
- shuffle: _bool_ determina si el split debe hacerse de manera random o no.

Hints: 

* Usar Indexing y slicing
* Usar np.random.[...]

In [ ]:
def split(X_input,
          Y_input,
          train_size=0.7,
          val_size=0.15,
          test_size=0.15,
          random_state=42,
          shuffle=True):
    
    return NotImplementedError