# Trabajo integrador - Parte 1
## Python y Numpy

**Nombre**:

In [1]:
import numpy as np
import math

## Ejercicio 1

Dada una matriz en formato *numpy array*, donde cada fila de la matriz representa un vector matemático, se requiere computar las normas $l_0$, $l_1$, $l_2$, $l_{\infty}$, según la siguientes definiciones:

\begin{equation}
    ||\mathbf{x}||^{p} = \bigg(\sum_{j=1}^{n}{|x_i|^p}\bigg)^{\frac{1}{p}}
\end{equation}

con los casos especiales para $p=0$ y $p=\infty$ siendo:

\begin{equation}
    \begin{array}{rcl}
        ||\mathbf{x}||_0 & = & \bigg(\sum_{j=1 \wedge x_j != 0}{|x_i|}\bigg)\\
        ||\mathbf{x}||_{\infty} & = & \max_{i}{|x_i|}\\
    \end{array}
\end{equation}

In [2]:
#Hecho como función

def normalp (vector,p):
    if p == 0:
        return len(vector[vector!=0])
    if p == "infinity" or "infinity" or "Infinito" or "infinito" or math.inf:
         return np.max(np.absolute(matrix_A))
    else:    
        absolute_vector=np.absolute(vector)
        to_the_p=absolute_vector**p
        sum1=np.sum(to_the_p)
        sum1_p_root=sum1**(1/p)
        return sum1_p_root

In [3]:
matrix_A= np.array([[-2,-4,2],[-2,1,2],[4,2,5]])

In [4]:
normalp (matrix_A,0)

9

In [5]:
normalp(matrix_A,"infinity")

5

In [6]:
normalp(matrix_A,2)

5

In [7]:
normalp(matrix_A,math.inf)

5

## Ejercicio 2

En clasificación contamos con dos arreglos, la “verdad” y la “predicción”. Cada elemento de los arreglos pueden tomar dos valores, “True” (representado por 1) y “False” (representado por 0). Entonces podemos definir 4 variables:

* True Positive (TP): El valor verdadero es 1 y el valor predicho es 1
* True Negative (TN): El valor verdadero es 0 y el valor predicho es 0
* False Positive (FP): El valor verdadero es 0 y el valor predicho es 1
* False Negative (FN): El valor verdadero es 1 y el valor predicho es 0

A partir de esto definimos:

* Precision = TP / (TP + FP)
* Recall = TP / (TP + FN)
* Accuracy = (TP + TN) / (TP + TN + FP + FN)
 
Calcular las 3 métricas con Numpy y operaciones vectorizadas.

In [8]:
def classification_metrics (verdad, prediccion):
    TP, TN, FP, FN = 0, 0, 0, 0

    with np.nditer([verdad, prediccion], flags=['multi_index'], op_flags=['readonly', 'readonly']) as i:
        for true, predicted in i:
            if true == 1 and predicted == 1:
                TP += 1
            elif true == 0 and predicted == 0:
                TN += 1
            elif true == 0 and predicted == 1:
                FP += 1
            elif true == 1 and predicted == 0:
                FN += 1

    precision = TP / (TP + FP)
    recall = TP / (TP + FN)
    accuracy = (TP + TN) / (TP + TN + FP + FN)
    
    print("Precision:", precision)
    print("Recall:", recall)
    print("Accuracy:", accuracy)
    

In [9]:
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

In [10]:
classification_metrics (truth, prediction)

Precision: 0.5
Recall: 0.5
Accuracy: 0.4


## Ejercicio 3

Crear una función que separe los datos en train-validation-test. Debe recibir de parametros:

- X: Array o Dataframe que contiene los datos de entrada del sistema.
- y: Array o Dataframe que contiene la(s) variable(s) target del problema.
- train_percentage: _float_ el porcentaje de training.
- test_percentage: _float_ el porcentaje de testing.
- val_percentage: _float_ el porcentaje de validación.
- shuffle: _bool_ determina si el split debe hacerse de manera random o no.

Hints: 

* Usar Indexing y slicing
* Usar np.random.[...]

In [26]:
def split(X_input,
          Y_input,
          train_size=0.7,
          val_size=0.15,
          test_size=0.15,
          random_state=42,
          shuffle=True):
    if train_size + val_size + test_size != 1.0:
        return "Los porcentajes deben sumar 1.0 (100%)."
    
    if shuffle:
        np.random.seed(random_state)
        indices = np.random.permutation(len(X_input))
    else:
        indices = np.arange(len(X_input))
    
    
    train_count = int(train_size * len(X_input))
    val_count = int(val_size * len(X_input))
    
    train_indices = indices[:train_count]
    val_indices = indices[train_count:train_count + val_count]
    test_indices = indices[train_count + val_count:]
    
    X_train = X_input[train_indices]
    Y_train = Y_input[train_indices]
    
    X_val = X_input[val_indices]
    Y_val = Y_input[val_indices]
    
    X_test = X_input[test_indices]
    Y_test = Y_input[test_indices]
    
    
    return X_train, Y_train, X_val, Y_val, X_test, Y_test, indices

#retorno indices solo para verificar abajo que el código funciona, no debería ir. 
#No entiendo qué es return notimplementederror, lo googleé y me dice que es para POO cuando necesitás
#una subclase en un método de una clase.

In [27]:
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [28]:
split(X,y)

(array([ 9,  2,  6,  1,  8,  3, 10]),
 array([0, 1, 1, 0, 1, 0, 1]),
 array([5]),
 array([0]),
 array([4, 7]),
 array([1, 0]),
 array([8, 1, 5, 0, 7, 2, 9, 4, 3, 6]))

In [29]:
split(X,y, shuffle=False)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 0, 1, 0, 1, 0]),
 array([8]),
 array([1]),
 array([ 9, 10]),
 array([0, 1]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))